---
categories:
- publications
comments: false
draft: false
showpagemeta: false
slug: ""
tags:
- publications
title: Publications
---

**Galloway, M**, Johnson, A., and Shemyakin, A. (2017). [Time-to-Default Analysis of Mortgage Portfolios](images/timetodefault.pdf). Model Assisted Statistics and Applications 12.4 (2017): 359-367. [[pdf](images/timetodefault.pdf)]

#### *"Mortgage defaults played a critical role in the recent (2008) financial crisis. Accordingly, the practice and foundations of subprime lending have received great attention in the literature. Crucial to these conversations is an understanding of the inherent risk in subprime lending. The following is an attempt to model the time-to-default (risk) of various mortgage cohorts using contemporary statistical modeling methods and two competing models. This is joint work with Dr. Arkady Shemyakin and Dr. Alicia Johnson."*


## Software

**Galloway, M.** (2018). CVglasso: Cross validation package for the popular *glasso* package. R package, https://cran.r-project.org/web/packages/CVglasso/index.html.

#### *"CVglasso is an R package that estimates a lasso-penalized precision matrix via block-wise coordinate descent – also known as the graphical lasso (glasso) algorithm. This package is a simple wrapper around the popular glasso package and extends and enhances its capabilities. These enhancements include built-in cross validation and visualizations."*

**Galloway, M.** (2018). ADMMsigma: Estimates a penalized precision matrix via the ADMM algorithm. R package, https://cran.r-project.org/web/packages/ADMMsigma/index.html.

#### *"ADMMsigma is an R package that estimates a penalized precision matrix via the alternating direction method of multipliers (ADMM) algorithm. It currently supports a general elastic-net penalty that allows for both ridge and lasso-type penalties as special cases."*

**Galloway, M.** (2018). SCPME: Shrinking Characteristics of Precision Matrix Estimators. R package, https://cran.r-project.org/web/packages/SCPME/index.html.

#### *"SCPME is an implementation of the methods described in “Shrinking Characteristics of Precision Matrix Estimators” ([link](https://academic.oup.com/biomet/article-abstract/105/3/563/4994725?redirectedFrom=fulltext)). It estimates a penalized precision matrix via a modified alternating direction method of multipliers (ADMM) algorithm."*
