---
categories:
- research
comments: false
draft: false
layout: noheader
showpagemeta: false
slug: ""
tags:
- research
title: Research
---

My research interests include statistical machine learning, multivariate analysis, precision matrix estimation, sufficient dimension reduction, and kernel methods (among others).

## R Packages

### [ADMMsigma](https://mgallow.github.io/ADMMsigma/)

Estimates a penalized precision matrix via the alternating direction method of multipliers (ADMM) algorithm.

### [Omega](https://mgallow.github.io/Omega/)

Estimates a penalized precision matrix via various estimation methods. OMEGA combines ADMMsigma and GLASSOO (along with other estimation methods) into a complete package.

### [GLASSOO](https://mgallow.github.io/GLASSOO/)

Estimates a penalized precision matrix via block-wise coordinate descent -- also known as the graphical lasso (glasso) algorithm.

### [CVglasso](https://mgallow.github.io/CVglasso/)

Estimates a penalized precision matrix. This package is a simple wrapper around the popular 'glasso' package and extends and enhances its capabilities.

### [logitr](https://mgallow.github.io/logitr/)

A package for linear and logistic regression with optional ridge and bridge regularization penalties.

### [statr](https://mgallow.github.io/statr/)

A personal R package that I have created for organization/convenience purposes.

<br>

## Miscellaneous Projects

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
</style>


<div class="col2">
- [statr](https://mgallow.github.io/statr/)
- [openfMRI Prediction](images/Openfmri_Voxel_Activity_Prediction.pdf)
- [STEM](images/Poster.pdf)
- [kernel methods](images/kernel.pdf)
- [indirect regression](images/Indirect.pdf)
</div>


## Gists

<div class="col2">
- [Travis Package Deployment](https://gist.github.com/MGallow/9759b2659b175233245c102e2b921231)
- [Simple ImageNet Classifier](https://gist.github.com/MGallow/f51fa54a1c57896293b5e89a7a945dab)
- [Weighted Ridge Regression](https://gist.github.com/MGallow/6f2763e9a36bb200a3cb4b264d144dae)
- [Random Forest](https://gist.github.com/MGallow/e91d35bd4994b08f6dc8508015b04861)
- [Slack-Notify Script](https://gist.github.com/MGallow/488f7df288701ad8bef7cf0a8f8b71ae)
</div>
