---
categories:
- about
comments: false
draft: false
showpagemeta: false
slug: ""
tags:
- about
title: About
---

Previously a consultant at the Institute for Research on Statistics and its Applications (IRSA) and Ph.D. student in statistics at the [University of Minnesota](https://cla.umn.edu/statistics). My research was advised by [Adam J. Rothman](http://users.stat.umn.edu/~arothman/), Ph.D. and broadly related to efficient precision matrix estimation. Currently working as a data scientist at C.H. Robinson in the Twin Cities area.

In May 2015, I received my B.S. and B.A. from the [University of St. Thomas, St. Paul](https://www.stthomas.edu/). I majored in statistics, mathematics, and actuarial science and minored in renaissance.

Please check out my [LinkedIn](https://www.linkedin.com/in/mattgalloway2/) for updates on my work experience.


# Education

**M.Sc.**, [School of Statistics](https://cla.umn.edu/statistics), *University of Minnesota*, 2019.

**B.S.**, **B.A.**, Statistics, Mathematics, Actuarial Science, [*University of St. Thomas*], 2015.

Actuarial Science, [*Heriot-Watt University*](margin-bottom: 20px;), Scotland, 2014.

[**RESUME**](images/WebsiteResume.pdf). [**CV**](images/CV.pdf). [**THESIS**](https://mattxgalloway.com/oral_manuscript/) ([**PDF**](https://mattxgalloway.com/oral_manuscript/Manuscript.pdf)).


# Teaching

Graduate instructor:

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
</style>


<div class="col2">
- STAT 3011 (Fall 2018)
</div>

<br>

Teaching assistantships:


<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
</style>


<div class="col2">
- STAT 1001 (Fall 2015)
- STAT 3032 (Spring 2016)
- STAT 3032 (Fall 2016)
- STAT 4893W (Spring 2017)
- IRSA Consultant (Fall 2017)
- STAT 8052 (Spring 2018)
</div>


# Consulting

I am periodically available for consulting on a private basis. Please contact me via email for inquiries: mattxgalloway@gmail.com.
